### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by TofPlay** [mozilla-mobile/ScrollingCardView#9]
Hi,
For iOS projets it's will be great to make your component [Carthage](https://github.com/Carthage/Carthage) compatible

Take a look at these articles: 
- [Ruthlessly Simple Dependency Management with Carthage](https://bit.ly/2IWvGks)
- [Carthage Tutorial: Getting Started](https://bit.ly/2zes4dN)
- [Making Carthage-compatible Frameworks with Swift](https://bit.ly/2tXUofp)
- [Swift Cross Platform Framework](https://bit.ly/2ysgETA) (section [Configure targets for Carthage](https://bit.ly/2tZUOSt)) 👍

On your `README.md` add [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage)  on top and add section for the installation with Carthage.

**Comment by mcomella** [comment]
I've gotten this most of the way there but I have other things to focus on and I don't have any immediate incentive to get this working. **If you want to use ScrollingCardView and lack of carthage support is holding you back, please let me know and I'll get to it ASAP!**

**Comment by sirvon** [comment]
@mcomella please continue getting this carthage ready! thank you

**Comment by mcomella** [comment]
Thanks for the ping @sirvon - I'll take a look tomorrow.

**Comment by mcomella** [comment]
Hey @sirvon – I've added Carthage support on master and updated the readme for installation instructions. Please let me know if you have any troubles!
